import turtle
wn = turtle.Screen()
wn.tracer(0)


t = turtle.Turtle()
t.hideturtle()
turtle.setup(700,500)
t.speed(0)
t.color("purple")
t.pensize("10")

def moveFd():
    x = t.xcor() - 220
    y = t.ycor()
    t.clear()
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.left(90)

    t.forward(35)
    t.penup()
    t.setpos(x + 65,-30)
    t.pendown()
    t.circle(30)
    t.penup()
    t.setpos(x + 95,0)
    t.pendown()
    t.fd(110)
    t.penup()
    t.setpos(x + 235,-30)
    t.pendown()
    t.circle(30)
    t.penup()
    t.setpos(x + 265,0)
    t.pendown()
    t.forward(35)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.fd(120)
    t.left(90)
    t.forward(50)
    t.right(90)
    t.forward(80)
    t.left(90)
    t.fd(50)
    t.penup()
    t.setpos(x + 55,0)
    t.pendown()
    t.circle(10)
    t.penup()
    t.setpos(x + 225,0)
    t.pendown()
    t.circle(10)
    wn.update()

def moveBd():
    x = t.xcor()- 235
    y = t.ycor()
    t.clear()
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.left(90)

    t.forward(35)
    t.penup()
    t.setpos(65 + x, -30)
    t.pendown()
    t.circle(30)
    t.penup()
    t.setpos(95 + x, 0)
    t.pendown()
    t.fd(110)
    t.penup()
    t.setpos(235 + x, -30)
    t.pendown()
    t.circle(30)
    t.penup()
    t.setpos(265 + x, 0)
    t.pendown()
    t.forward(35)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(100)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.fd(120)
    t.left(90)
    t.forward(50)
    t.right(90)
    t.forward(80)
    t.left(90)
    t.fd(50)
    t.penup()
    t.setpos(55 + x, 0)
    t.pendown()
    t.circle(10)
    t.penup()
    t.setpos(225 + x, 0)
    t.pendown()
    t.circle(10)
    wn.update()
    

t.forward(35)
t.penup()
t.setpos(65,-30)
t.pendown()
t.circle(30)
t.penup()
t.setpos(95,0)
t.pendown()
t.fd(110)
t.penup()
t.setpos(235,-30)
t.pendown()
t.circle(30)
t.penup()
t.setpos(265,0)
t.pendown()
t.forward(35)
t.left(90)
t.forward(50)
t.left(90)
t.forward(100)
t.right(90)
t.forward(50)
t.left(90)
t.fd(120)
t.left(90)
t.forward(50)
t.right(90)
t.forward(80)
t.left(90)
t.fd(50)
t.penup()
t.setpos(55,0)
t.pendown()
t.circle(10)
t.penup()
t.setpos(225,0)
t.pendown()
t.circle(10)
wn.update()
print(t.pos())

wn.onkey(moveFd, 'Right')
wn.onkey(moveBd, 'Left')

wn.listen()
wn.mainloop()
